# Generated by Django 3.0.4 on 2020-05-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0033_auto_20200530_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
