# Generated by Django 3.0.4 on 2020-04-05 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.CharField(max_length=30)),
                ('specified_as', models.CharField(choices=[('New', 'NEW'), ('Pickup', 'PICKUP')], max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('requested_on', models.DateField(null=True)),
                ('granted_on', models.DateField(null=True)),
                ('caption', models.TextField(max_length=300)),
                ('source', models.CharField(max_length=75)),
                ('status', models.CharField(choices=[('Requested', 'REQUESTED'), ('Approved', 'APPROVED'), ('Followed Up', 'FOLLOWED UP')], max_length=15)),
                ('source_link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=75)),
                ('author_email_id', models.EmailField(max_length=254)),
                ('alternative_email_id', models.EmailField(max_length=254)),
                ('notes', models.TextField(max_length=300)),
                ('rh_address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('insert_1', models.CharField(max_length=100)),
                ('jbl_rh_name', models.CharField(max_length=75)),
                ('file_location', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=40)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=30)),
                ('chapter_title', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='permissions.Book')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedup_at', models.DateField(null=True)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='permissions.Element')),
                ('followedup_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='permissions.Unit'),
        ),
        migrations.AddField(
            model_name='element',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
