# Generated by Django 3.0.4 on 2020-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0018_element_permission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='denied_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
