# Generated by Django 3.2.7 on 2021-10-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0043_rename_rs_name_element_jbl_rh_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='rh_email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
