# Generated by Django 3.0.4 on 2020-05-03 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0015_auto_20200420_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='specified_as',
        ),
        migrations.RemoveField(
            model_name='element',
            name='status',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
