# Generated by Django 3.0.4 on 2020-05-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0032_auto_20200530_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='alt_email',
        ),
        migrations.RemoveField(
            model_name='element',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='element',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='element',
            name='rh_address',
        ),
        migrations.RemoveField(
            model_name='element',
            name='rh_email',
        ),
    ]
