# Generated by Django 3.0.4 on 2020-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0022_element_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(blank=True, choices=[('Cover', 'Cover'), ('Photo', 'Photo'), ('Art', 'Art'), ('Text', 'Text'), ('CaseStudy', 'CaseStudy'), ('Combo', 'Combo'), ('Fig', 'Screenshot'), ('Table', 'Table')], max_length=25),
        ),
        migrations.AlterField(
            model_name='element',
            name='rh_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
