# Generated by Django 3.0.4 on 2020-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_auto_20200516_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
