# Generated by Django 3.0.4 on 2020-04-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
