# Generated by Django 3.0.4 on 2020-06-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0038_auto_20200614_0006'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='element',
            managers=[
            ],
        ),
    ]
