# Generated by Django 3.0.4 on 2020-04-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20200408_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='credit_line',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
