# Generated by Django 3.0.4 on 2020-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0010_auto_20200419_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='insert_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='source_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
