# Generated by Django 3.0.4 on 2020-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0011_auto_20200419_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='file_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='file_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='rh_address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
