# Generated by Django 3.0.4 on 2020-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0014_auto_20200419_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='granted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
