# Generated by Django 3.0.4 on 2020-05-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_auto_20200516_1312'),
        ('permissions', '0024_auto_20200523_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='publisher.Publisher'),
        ),
        migrations.AlterField(
            model_name='element',
            name='requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
