# Generated by Django 3.0.4 on 2020-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0026_auto_20200525_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='source_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
