# Generated by Django 3.0.4 on 2020-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0036_auto_20200531_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='rh_email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
