# Generated by Django 3.2.7 on 2021-10-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0041_auto_20211022_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='desciption',
            new_name='description',
        ),
    ]
