# Generated by Django 3.2.7 on 2021-11-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0044_element_rh_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='rh_address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
