# Generated by Django 3.2.7 on 2022-01-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0047_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='text_data',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(blank=True, choices=[('Cover', 'Cover'), ('Photo', 'Photo'), ('Art', 'Art'), ('Text', 'Text'), ('Box', 'Box'), ('CaseStudy', 'CaseStudy'), ('Combo', 'Combo'), ('Fig', 'Screenshot'), ('Table', 'Table')], max_length=25),
        ),
    ]
