# Generated by Django 3.2.7 on 2022-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0050_element_rh_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='rh_email',
            field=models.TextField(null=True, unique=True),
        ),
    ]
