# Generated by Django 3.0.4 on 2020-05-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0020_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
