# Generated by Django 3.0.4 on 2020-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0021_auto_20200517_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.CharField(blank=True, choices=[('Cover', 'CVR'), ('Photo', 'FIG'), ('Art', 'FIG'), ('Text', 'FTR'), ('Case Study', 'FTR'), ('Combo', 'FIG'), ('Screenshot', 'FIG'), ('Table', 'TAB')], max_length=25),
        ),
    ]
