# Generated by Django 3.0.4 on 2020-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20200406_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='alternative_email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='author_email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='author_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='caption',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='fax',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='file_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='file_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='insert_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='jbl_rh_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='notes',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='rh_address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='source',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='source_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
