# Generated by Django 3.0.4 on 2020-05-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='updated_at',
        ),
    ]
