# Generated by Django 3.0.4 on 2020-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0030_auto_20200530_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='caption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='credit_line',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
