# Generated by Django 3.0.4 on 2020-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_publisher_publisher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_imprint',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
