# Generated by Django 3.0.4 on 2020-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0031_auto_20200530_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='caption',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
