# Generated by Django 3.0.4 on 2020-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_auto_20200419_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='caption',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='credit_line',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='file_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='file_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='insert_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='jbl_rh_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='rh_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='source',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='source_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='specified_as',
            field=models.CharField(blank=True, choices=[('Killed', 'KILLED'), ('New', 'NEW'), ('Pickup', 'PICKUP'), ('Re-use', 'RE-USE'), ('Revised', 'REVISED')], max_length=25),
        ),
        migrations.AlterField(
            model_name='element',
            name='status',
            field=models.CharField(blank=True, choices=[('Filled', 'FILLED'), ('In Review', 'IN REVIEW'), ('Invoice Requested', 'INVOICE REQUESTED'), ('Killed', 'KILLED'), ('TK from Author', 'TK FROM AUTHOR'), ('Need AU Confirmation', 'NEED AU CONFIRMATION'), ('Need Comp Copy', 'NEED COMP COPY'), ('Need Invoice', 'NEED INVOICE'), ('Need PD Confirmation', 'NEED PD CONFIRMATION'), ('Need Permission', 'NEED PERMISSION'), ('Perm Requested', 'PERM REQUESTED'), ('Photo Shoot', 'PHOTO SHOOT'), ('Processing Image', 'PROCESSING IMAGE'), ('Research', 'RESEARCH'), ('Create Original', 'CREATE ORIGINAL')], max_length=25),
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
