# Generated by Django 3.0.4 on 2020-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0028_auto_20200530_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rh_firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rh_lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='rh_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
